### Get list template file
GET http://localhost:3210/v1/template-file
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVkZDcwNTQ0LWY3M2UtMTFlZi05ZWI0LTA4OTc5OGQzIiwiaWF0IjoxNzQxMzIxMzAwLCJleHAiOjE3NDE0MDc3MDB9._3zA8fKNqGs7o4neDSR1H_QkYSvWMUqf-gNRC-fEVH0
